resolver: lts-14.21

packages:
- .

extra-deps:
- amazonka-1.6.1
- git: https://github.com/simonkaltenbacher/amazonka.git
  commit: 3caefbf266d84dbfa0f720a629d41a36fe173bcc
  subdirs:
  - amazonka-cloudformation
- amazonka-core-1.6.1
- amazonka-s3-1.6.1
- dhall-1.29.0
- prettyprinter-1.6.0
- prettyprinter-ansi-terminal-1.1.1.2

ghc-options:
  "$locals": -fwarn-unused-imports